### ISSUE TITLE
Better Error Handling when description for contract is wrong

### ISSUE THREAD

**Issue by tgxworld** [gsmendoza/verified_double#32]
![tinygrab screen shot 2-10-14 12 30 42 pm](https://f.cloud.github.com/assets/4335742/2130385/48ff7060-9292-11e3-9dd0-116b4f3c26ca.png)

This happened when I left out `#` from the description.

**Comment by gsmendoza** [comment]
Sorry @tgxworld it took a while for me to reply. Rest assured, we already have someone who'll fix this issue for you! :D
